version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony_app
    mem_limit: 512m
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: mysql://db_user:db_password@db:3306/db_name
    depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: